# Generated by Django 5.0.6 on 2024-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
